# Generated by Django 5.0 on 2026-07-24 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('account_number', models.CharField(max_length=20)),
                ('iban', models.CharField(max_length=30)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('receipt_no', models.CharField(max_length=20, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=12)),
                ('receiver_bank', models.CharField(max_length=100)),
                ('receiver_iban', models.CharField(max_length=30)),
                ('receiver_name', models.CharField(max_length=100)),
                ('transaction_type', models.CharField(choices=[('FAST', 'FAST işlemi'), ('HAVALE', 'Havale işlemi'), ('EFT', 'EFT işlemi')], default='FAST', max_length=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='api.customer')),
            ],
        ),
    ]
