# Generated by Django 5.0 on 2026-07-24 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='branch',
            field=models.CharField(default='0010/İSKENDERUN/HATAY ŞUBESİ', max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='tc',
            field=models.CharField(default='11111111111', max_length=11),
        ),
        migrations.AddField(
            model_name='transaction',
            name='amount_in_words',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='transaction',
            name='bsmv',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='transaction',
            name='komisyon',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='transaction',
            name='mesaj_ucreti',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
