# Generated by Django 5.0 on 2026-07-24 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_transaction_is_incoming_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='receiver_iban',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
