# Generated by Django 5.0 on 2026-07-24 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_transaction_receiver_iban'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='initial_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
