# Generated by Django 5.0 on 2026-07-24 15:46

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_transaction_receipt_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='receipt_file',
            field=models.FileField(blank=True, null=True, upload_to=api.models.receipt_upload_path),
        ),
    ]
