# Generated by Django 5.0 on 2026-07-24 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_transaction_receipt_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='iban',
            field=models.CharField(max_length=100),
        ),
    ]
