# Generated by Django 5.0 on 2026-07-25 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_customer_iban'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='receiver_account',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
