# Generated by Django 5.0 on 2026-07-25 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_transaction_receiver_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='receiver_branch',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
