# Generated by Django 5.0 on 2026-08-06 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_transaction_receiver_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='fast_sorgu_no',
            field=models.CharField(blank=True, default='69402342304', max_length=50),
        ),
    ]
